# Generated by Django 6.1.1 on 2026-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Note')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
