# Generated by Django 6.1.1 on 2026-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, default='Untitled Note', max_length=255),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(verbose_name='Note'),
        ),
    ]
